### PR TITLE
Adds crop-growth flag.

### PR DESCRIPTION
**Pull request by flaminscotsman**
This adds a region flag (crop-growth) and a configuration option (dynamics.disable-crop-growth) to stop the growth of wheat, potato and carrot plants.

### CODE REVIEW

**Comment by ThatGamerBlue** [comment]
bump

**Comment by Ugikie** [comment]
Did this ever get added?

**Comment by flaminscotsman** [comment]
Nope, although I can look at updating it to match the current project structure if people want it?

**Comment by Ugikie** [comment]
That would be amazing, I'm sure people could benefit from this as I have heard of people asking about it before. Hope it can get done! :)

**Comment by wizjany** [comment]
Uh, this is so old I didn't even realize it existed, but since someone made a ticket recently I've added this myself.

**Pull request closed without merging**
