### PR TITLE
Spongeable lava

### PR DESCRIPTION
**Pull request by Terrobility**
I saw yet another big server adding spongeable lava (where sponges work on lava) so I decided to just add this straight into WorldGuard. I've tried it on my server and it works as intended, however you may want to have a look at it as usual :P

### CODE REVIEW

**Comment by HunterGPlays** [comment]
Image of spongeable lava in action

**Comment by DahFrozen** [comment]
I would love this! Please add it! I don't see any harm in it.

**Comment by DarkArc** [comment]
There needs to be a new configuration option for this.

**Comment by HunterGPlays** [comment]
I'll add one in on Friday.

-----Original Message-----

**Comment by HunterGPlays** [comment]
Maybe I'll add it now, not on Friday :heart:

**Comment by HunterGPlays** [comment]
I can confirm it works as intended, even with redstone sponges enabled. My changes are fairly simple; there should be nothing wrong with it.

**Comment by HunterGPlays** [comment]
@DarkArc I can confirm it works as intended, even with redstone sponges enabled. My changes are fairly simple; there should be nothing wrong with it.

**Comment by DarkArc** [comment]
@HunterGPlays well, unfortunately I don't do work on Bukkit anymore. So, someone else is going to have to verify that. However, I still think this could use some improvement. 

Could you make the configuration for this set up in such a way that you can also use the lava sponge without using the water sponge. Perhaps add a new config node:
````java
spongeWorksOnWater = getBoolean("simulation.sponge.absorbs-water", true); 
````

That way existing configurations aren't impacted, and there's more fine grained control over what actually happens.

**Comment by HunterGPlays** [comment]
I'll give it a shot and get back to you.

-----Original Message-----

**Comment by HunterGPlays** [comment]
I've tried to add this in however there's no SpongeSoakEvent or anything similar. I will have to create a workaround to prevent vanilla sponge behaviour when sponges is set to true in the config.

**Comment by HunterGPlays** [comment]
I'll upload a gif to show the bug with vanilla sponge behaviour

**Comment by HunterGPlays** [comment]
Spongeable water conflicting with vanilla behaviour

**Comment by HunterGPlays** [comment]
Spongeable water vanilla conflict

**Comment by HunterGPlays** [comment]
@DarkArc There's no way for me to make sponges not work with water. The best I can do is add a config option for WorldGuard overriding vanilla sponge behaviour when it comes to absorbing water. There's no event as far as I know that handles sponges absorbing water.

**Comment by DarkArc** [comment]
@HunterGPlays right yes, I didn't intended to ask you to kill the current Vanilla sponge behavior. I just meant that you should be able to turn on your new WorldGuard simulate lava sponge thing, wtihout turning on WorldGuard simulation of the old-timey sponge.

This looks like it should be fine, just glimpsing over your changes, thanks.

**Comment by HunterGPlays** [comment]
The force update on sponge break is bugged, I wouldn't merge it.

**Comment by HunterGPlays** [comment]
I've had my changes tested by @DahFrozen and he's made sure that there's no bugs.

**Comment by DahFrozen** [comment]
I can confirm that Spongable Lava and Water do work as intended. I look forward to see this in the official release :D

    sponge:
        enable: true
        radius: 3
        redstone: false
        absorbs-lava: true
        convert-wet-to-dry: true
        override-vanilla-water-behaviour: true
        force-update-on-sponge-break: true

**Comment by HunterGPlays** [comment]
Any updates? @DarkArc

**Pull request closed without merging**
